//! Utilities for dealing with fields in programmable logic bitstreams
//!
//! "Achieving more by codegenning _less_"
//!
//! The purpose of this crate is to solve one specific problem:
//! A programmable logic device (typically an FPGA) contains settings
//! which are configured using what in software terms would be bitfields.
//! However, they often contain "don't care" bits (e.g. both `10` and `11`
//! might represent the same "use the special wire" setting).
//! The bits are also often _not_ contiguous. It would be nice to eliminate
//! the redundancies involved in this encoding/decoding process.
//!
//! Previous attempts have run into the following issues:
//! - attempting to generate both bit encoding/decoding code *and*
//!   human-readable-formatting code at the same time tended to make
//!   the code unmaintainable, as there was _too much_ opaque autogenerated code
//! - using `&[bool]` or `[bool; N]` in the API surface can cause performance cliffs
//!   depending on how the optimizer/inliner is feeling that day
//! - attempting to capture and/or bubble invalid values clutters up the API
//!   (typically we _know for sure_ the values are invalid)
//! - integrating this with codegenning the rest of the structure made the
//!   "too much autogenerated code" problem even worse
//!
//! As such, this version now does a lot less and is more self-contained:
//! - the user/caller must manually implement the [BitGetter]/[BitSetter] traits.
//!   that external implementation will handle mapping "this thingy"-relative bit coordinates
//!   to tile-relative and global coordinates within the bitstream,
//!   but the details are no longer exposed to _this_ crate.
//! - this code now uses [mod@bitvec] to pre-collect the field's bits into a primitive integer,
//!   so that matching will _always_ be done using bit masking. this does end up enforcing an
//!   (acceptable) upper limit on the size of each bitfield.
//! - invalid values will now panic, rather than attempting to capture or represent invalid states.
//!   it is intended that applications using this crate behave as follows:
//!   - unknown setting values should be reverse-engineered and documented.
//!     this may involve identifying "don't care" bits that vendor tools don't generate.
//!   - _very_ corrupted files just panic, since the only way to create one will be manual hex editing
//! - doesn't handle human-readable formatting, [Default], etc. anymore

#![no_std]

use bitvec::prelude::*;

/// Hardcode that each field can be encoded with at most 32 bits
type FieldPackedBitsTy = u32;

/// Trait for reading bits for a bitstream field (enum, mux, etc.)
///
/// The intended application is to implement this on a wrapper struct
/// similar to the following:
/// ```
/// # use core::borrow::Borrow;
/// # use bitmux::BitGetter;
/// # struct Bitstream(u32);
/// # impl Bitstream {
/// #   fn get(&self, _idx: usize) -> bool { false }
/// # }
/// #
/// struct EnumRef<B: Borrow<Bitstream>> {
///     b: B,
///     this_field_idx: usize,
///     this_tile_pos: (u32, u32),
///     // ...
/// }
/// impl<B: Borrow<Bitstream>> BitGetter for EnumRef<B> {
///     #[inline]
///     fn get_bit(&self, biti: usize) -> bool {
///         let bits = self.b.borrow();
///         // Example of somehow converting `biti` to the appropriate index
///         let idx = self.this_tile_pos.0 as usize + self.this_field_idx + biti;
///         bits.get(idx)
///     }
/// }
/// ```
///
/// In most cases, there will be a _unique_ pairing between
/// each wrapper type which implements `BitGetter`
/// (e.g. a hypothetical `struct LutCarryRef`) and
/// each field (e.g. a hypothetical `enum LutCarryInput`).
/// However, because FPGAs always end up with exceptions,
/// this isn't encoded into the macro-based code generation
/// and must be dealt with _manually_ (by "just" calling with
/// the correct types and never calling with the wrong types).
/// Previous attempts to check this within the Rust type system
/// resulted in _more_ unmaintainable complexity, and
/// this pairing does not ever need to change once it works.
pub trait BitGetter {
    /// Return the `biti`-th bit in the encoding of this field
    fn get_bit(&self, biti: usize) -> bool;

    #[inline]
    /// Automatically collect the bits for this field into a primitive integer
    fn get_bits<const N: usize>(&self) -> FieldPackedBitsTy {
        assert!(N <= u32::BITS as usize, "bitfield cannot use >32 bits");
        let mut bits = 0u32;
        let bits_ = BitSlice::<_, Lsb0>::from_element_mut(&mut bits);
        for i in 0..N {
            bits_.set(i, self.get_bit(i));
        }
        bits
    }
}

/// Trait for writing a bitstream field's (enum, mux, etc.) bits into a bitstream
///
/// See the [BitGetter] documentation for more context.
pub trait BitSetter {
    /// Write the `biti`-th bit of this field's encoding into `self`
    fn set_bit(&mut self, biti: usize, val: bool);

    #[inline]
    /// Automatically write all bits for this field into `self`
    fn set_bits<const N: usize>(&mut self, val: FieldPackedBitsTy) {
        assert!(N <= u32::BITS as usize, "bitfield cannot use >32 bits");
        let val = BitSlice::<_, Lsb0>::from_element(&val);
        for i in 0..N {
            self.set_bit(i, val[i]);
        }
    }
}

/// Trait for a particular type of bitfield within a bitstream
///
/// This will be auto-implemented by proc macro for a bitstream enum,
/// and it can also be manually implemented.
pub trait BitstreamField {
    /// Read the enum from a [BitGetter] handle
    fn get(b: impl BitGetter) -> Self;
    /// Write ourself into a [BitSetter] handle
    fn set(&self, b: impl BitSetter);
}

/// Macro to generate enum field
///
/// This accepts input like the following:
///
/// ```
/// # use bitmux::bitenum;
/// #[bitenum]
/// #[derive(Clone, Copy, PartialEq, Eq, Debug)]
/// enum HypotheticalFPGASetting {
///     UseSuperFastPath = "x00",
///     UseNormalPath = "x01",
///     DontUseAnyPaths = "X1X",
/// }
/// ```
///
/// The result will be an automagic implementation of the [BitstreamField] trait.
///
/// ## Bit patterns
///
/// Bit patterns are strings specifying how to encode a given setting in the bitstream.
/// Each character corresponds to a single bit.
///
/// The valid characters for the string are `0`, `1`, `x`, and `X`.
/// - `0` and `1` correspond to a `0` or `1` bit (obviously).
/// - `x` is a don't-care while reading but will be written as `0` when writing.
/// - `X` is a don't-care while reading but will be written as `1` when writing.
///
/// All bit patterns must be the same length, and this length must be &leq; 32 bits.
///
/// ## Bit ordering
///
/// The rightmost bit in the string literal is numbered `0`.
///
/// With an example:
/// ```text
/// "x01"
///  ^ ^
///  | |
///  | +- bit 0
///  +--- bit 2
/// ```
///
/// ## Customizing error handling
///
/// By default, the macro will generate the following default match arm:
///
/// ```ignore
/// _ => panic!("invalid bit pattern {bits:0width$b}", width = 3 /* or appropriate width */)
/// ```
///
/// In the unlikely event that this is not sufficient, it is possible to
/// customize this by using a special identifier of `err`:
///
/// ```
/// # use bitmux::bitenum;
/// #[bitenum]
/// enum ErrExample {
///     SomeSetting = "x00",
///     err = {
///         // do something else?
///         panic!("my custom error")
///     }
/// }
/// ```
///
/// ## Full syntax
///
/// The full syntax accepted by this macro is as follows:
/// ```
/// # use bitmux::bitenum;
/// #[bitenum(
///     crate = ::bitmux,   // It is possible to customize the path to the `bitmux` crate
/// )]
/// /// Doc comments will be propagated, as will other attributes
/// pub(crate) // A visibility specifier is permitted
/// enum FullExample {
///     /// Doc comments and attributes here will propagate as well
///     VariantA = "0000",
///     /// This will be written as "0011"
///     VariantB = "xxX1",
///     // err = /* This space can be either an expression or a block */ Self::VariantA
///     err = { Self::VariantA } // ... but only _one_, not multiple `err`
/// }
/// ```
pub use bitmux_macros::bitenum;

/// Macro to generate `match` for two-hot muxes
///
/// This is intended to be used like as follows:
/// ```
/// # use bitmux::*;
/// #[derive(Debug)]
/// enum ExampleMux {
///     GND,
///     Input(u8)
/// }
///
/// impl BitstreamField for ExampleMux {
///     fn get(b: impl BitGetter) -> Self {
///         let bits = b.get_bits::<9>();
///         twohot!(4, 5, match bits {
///             #bits => Self::Input(#val),
///             0 => Self::GND,
///             _ => panic!("invalid mux setting {bits:09b}")
///         })
///     }
///
///     fn set(&self, mut b: impl BitSetter) {
///         b.set_bits::<9>(twohot!(4, 5, match self {
///             Self::Input(#val) => #bits,
///             Self::GND => 0,
///             _ => panic!("invalid mux setting {self:?}")
///         }));
///     }
/// }
/// ```
///
/// ## What is a two-hot mux
///
/// A two-hot mux selects one output from amongst its m⋅n possible inputs.
/// It uses only m+n control bits rather than m⋅n control bits that a one-hot mux would need.
/// It can be thought of as two layers of one-hot muxes: an "inner" layer of n muxes
/// all sharing the same m control bits, followed by an "outer" layer of 1 mux
/// selecting one choice from amongst the n "inner" muxes.
///
/// The raw encoding of each value consists of exactly two 1 bits.
/// One bit must be set in the group of m "inner" control bits,
/// and the other must be set in the group of n "outer" control bits.
/// The remaining bits must all be 0.
///
/// For example, with 5 control bits, a one-hot mux can select amongst 5 possible inputs.
/// However, by dividing it into a 3+2 bit two-hot mux, it can select amongst 6 possible inputs:
///
/// ```text
/// A --|\
/// B --| |-------+
/// C --|/        |
///      ¦        +-|\
/// D --|\          | |-- O
/// E --| |---------|/
/// F --|/           ¦
///      ¦           ¦
///      ¦           ¦
/// inner mux        ¦
/// 3 control bits   ¦
///             outer mux
///             2 control bits
/// ```
///
/// This continues to scale well as the number of inputs increases.
/// Two-hot muxes are a common feature of FPGA bitstreams because it is a good trade-off
/// between hardware design complexity and the amount of space used in the bitstream.
///
/// ## The `twohot!` macro
///
/// The `twohot!(outer, inner, match expr { ... })` macro takes
/// two integer literal bit counts ("simple" base-10 syntax only),
/// followed by a `match` statement.
///
/// The first item inside the `match` statement _must_ be a special template of the form:
/// - `#bits => /* some expr */`
/// - `/* some expr */ => #bits`
///
/// and must end with a comma. This item will be replaced with autogenerated code.
/// The `match` statement can (and likely must) contain additional items
/// (e.g. default cases), and these will be copied to the output directly.
///
/// The template will be repeated for each possible mux input.
/// `#bits` will be replaced with the numeric value of the raw encoding (e.g. `0b10010`),
/// and, within `/* some expr */`, `#val` will be replaced with the index of the input.
///
/// For example, in the above sample code's `get` function, the autogenerated code
/// will look like the following:
/// ```ignore
/// 0b000100001 => Self::Input(0),
/// 0b000100010 => Self::Input(1),
/// 0b000100100 => Self::Input(2),
/// 0b000101000 => Self::Input(3),
/// 0b000110000 => Self::Input(4),
/// 0b001000001 => Self::Input(5),
/// // ...
/// ```
///
/// ## Bit ordering
///
/// The first integer literal specifies the size of the "outer" mux,
/// which is applied to the outputs of the "inner" muxes.
/// The second integer literal specifies the size of each "inner" mux.
///
/// The inner mux bits occupy the least significant bits of the input,
/// and the outer mux bits occupy the more significant bits afterwards.
///
/// ```ignore
///     0b0001_00001 => Self::Input(0),
///     0b0001_00010 => Self::Input(1),
///     0b0001_00100 => Self::Input(2),
///     0b0001_01000 => Self::Input(3),
///     0b0001_10000 => Self::Input(4),
///     0b0010_00001 => Self::Input(5),
/// //    \__/ \___/
/// //     |     |
/// //     |     +- inner
/// //     +------- outer
/// ```
///
/// The equivalent numeric index is
/// (outer mux choice) * (size of inner muxes) + (inner mux choice).
/// The mux choices start counting from 0 when the position of the 1 bit
/// is in its least-significant position and counts up as the 1 bit moves
/// to more-significant positions:
///
/// ```ignore
/// // Five possible inner mux inputs
/// 0b0001_00001 => Self::Input(0),
/// 0b0001_00010 => Self::Input(1),
/// 0b0001_00100 => Self::Input(2),
/// 0b0001_01000 => Self::Input(3),
/// 0b0001_10000 => Self::Input(4),
/// // Cycled through all inner mux inputs, advance outer mux
/// 0b0010_00001 => Self::Input(5),
/// 0b0010_00010 => Self::Input(6),
/// 0b0010_00100 => Self::Input(7),
/// 0b0010_01000 => Self::Input(8),
/// 0b0010_10000 => Self::Input(9),
/// // ...
/// ```
pub use bitmux_macros::twohot;

#[cfg(test)]
mod tests {
    mod test_bit_getter_setter {
        use super::super::*;

        impl BitGetter for u32 {
            fn get_bit(&self, biti: usize) -> bool {
                let self_ = BitSlice::<_, Lsb0>::from_element(self);
                self_[biti]
            }
        }
        impl BitSetter for u32 {
            fn set_bit(&mut self, biti: usize, val: bool) {
                let self_ = BitSlice::<_, Lsb0>::from_element_mut(self);
                self_.set(biti, val);
            }
        }

        #[test]
        fn test() {
            let mut x = 0x123u32;
            assert_eq!(x.get_bits::<32>(), 0x123);
            assert_eq!(x.get_bits::<8>(), 0x23);
            assert_eq!(x.get_bits::<4>(), 0x3);

            x.set_bits::<8>(0x345);
            assert_eq!(x, 0x145);
            x.set_bits::<4>(0x456);
            assert_eq!(x, 0x146);
        }
    }

    mod test_enum {
        use super::super::*;
        use core::borrow::{Borrow, BorrowMut};

        #[bitenum(crate = crate)]
        #[derive(Clone, Copy, PartialEq, Eq, Debug)]
        enum TestEnum {
            ValA = "x00",
            ValB = "x01",
            ValC = "X1X",
        }

        struct EnumRef<B: Borrow<u32>> {
            b: B,
            idx: usize,
        }

        impl<B: Borrow<u32>> BitGetter for EnumRef<B> {
            fn get_bit(&self, biti: usize) -> bool {
                let bits = self.b.borrow();
                let bits = BitSlice::<_, Lsb0>::from_element(bits);
                bits[self.idx * 4 + biti]
            }
        }
        impl<B: BorrowMut<u32>> BitSetter for EnumRef<B> {
            fn set_bit(&mut self, biti: usize, val: bool) {
                let bits = self.b.borrow_mut();
                let bits = BitSlice::<_, Lsb0>::from_element_mut(bits);
                bits.set(self.idx * 4 + biti, val);
            }
        }

        #[test]
        fn test() {
            let mut x = 0x5234u32;
            assert_eq!(TestEnum::get(EnumRef { b: &x, idx: 0 }), TestEnum::ValA);
            assert_eq!(TestEnum::get(EnumRef { b: &x, idx: 1 }), TestEnum::ValC);
            assert_eq!(TestEnum::get(EnumRef { b: &x, idx: 2 }), TestEnum::ValC);
            assert_eq!(TestEnum::get(EnumRef { b: &x, idx: 3 }), TestEnum::ValB);

            TestEnum::ValC.set(EnumRef { b: &mut x, idx: 0 });
            assert_eq!(x, 0x5237);
            TestEnum::ValA.set(EnumRef { b: &mut x, idx: 1 });
            assert_eq!(x, 0x5207);
            TestEnum::ValB.set(EnumRef { b: &mut x, idx: 2 });
            assert_eq!(x, 0x5107);
        }
    }
}
