use super::*;

pub const TMUX_MAP: [[TMUXSource; 15]; 16] = [
    // TMUX 0
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::GlobalToLocal(0),
    ],
    // TMUX 1
    [
        TMUXSource::RMUX(1),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 0,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::GlobalToLocal(0),
    ],
    // TMUX 2
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 1,
        }),
        TMUXSource::RMUX(74),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 1,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::GlobalToLocal(1),
    ],
    // TMUX 3
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 2,
        }),
        TMUXSource::RMUX(51),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 2,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::GlobalToLocal(1),
    ],
    // TMUX 4
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::GlobalToLocal(2),
    ],
    // TMUX 5
    [
        TMUXSource::RMUX(31),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 3,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::GlobalToLocal(2),
    ],
    // TMUX 6
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 4,
        }),
        TMUXSource::RMUX(8),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 4,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::GlobalToLocal(3),
    ],
    // TMUX 7
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 5,
        }),
        TMUXSource::RMUX(81),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 5,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::GlobalToLocal(3),
    ],
    // TMUX 8
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::GlobalToLocal(4),
    ],
    // TMUX 9
    [
        TMUXSource::RMUX(61),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 6,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::GlobalToLocal(4),
    ],
    // TMUX 10
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 7,
        }),
        TMUXSource::RMUX(38),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 7,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::GlobalToLocal(5),
    ],
    // TMUX 11
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 8,
        }),
        TMUXSource::RMUX(15),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 8,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::GlobalToLocal(5),
    ],
    // TMUX 12
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 12,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 12,
        }),
        TMUXSource::Unused,
    ],
    // TMUX 13
    [
        TMUXSource::RMUX(91),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 9,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 13,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 13,
        }),
        TMUXSource::Unused,
    ],
    // TMUX 14
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 10,
        }),
        TMUXSource::RMUX(68),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 10,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 1,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 2,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::N,
            bundle: 3,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 14,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 14,
        }),
        TMUXSource::Unused,
    ],
    // TMUX 15
    [
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 1,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 2,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::W,
            bundle: 3,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 1,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 2,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::S,
            bundle: 3,
            wire_idx: 11,
        }),
        TMUXSource::RMUX(45),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 1,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T4,
            going_dir: Direction::E,
            bundle: 2,
            wire_idx: 11,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::E,
            bundle: 0,
            wire_idx: 15,
        }),
        TMUXSource::RoutingWire(RoutingWire {
            ty: WireType::T1,
            going_dir: Direction::W,
            bundle: 0,
            wire_idx: 15,
        }),
        TMUXSource::Unused,
    ],
];
