//! Information about physical packages

pub enum PinFunction {
    /// Power supply pin
    VDD,
    /// Power supply pin
    GND,
    /// Not connected
    NC,
    /// Some kind of special function
    Special(&'static str),
    /// An IO pad, with the given internal padring index
    IO(u8),
}

pub const AGRV2K_QFP100_PINS: [PinFunction; 100] = [
    // pin 1
    PinFunction::IO(33),
    PinFunction::IO(32),
    PinFunction::IO(31),
    PinFunction::IO(30),
    PinFunction::IO(29),
    PinFunction::Special("VBAT"),
    PinFunction::IO(28),
    PinFunction::Special("OSC32_IN"),
    PinFunction::Special("OSC32_OUT"),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::Special("OSC_IN"),
    PinFunction::Special("OSC_OUT"),
    PinFunction::Special("nRST"),
    PinFunction::IO(27),
    PinFunction::IO(26),
    PinFunction::IO(25),
    PinFunction::IO(24),
    PinFunction::NC,
    PinFunction::GND,
    PinFunction::Special("VREFP"),
    PinFunction::VDD,
    PinFunction::IO(21), // note reordering here
    PinFunction::IO(22),
    PinFunction::IO(23),
    // pin 26
    PinFunction::IO(20),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(19),
    PinFunction::IO(18),
    PinFunction::IO(17),
    PinFunction::IO(16),
    PinFunction::IO(15),
    PinFunction::IO(14),
    PinFunction::IO(13),
    PinFunction::IO(12),
    PinFunction::IO(11),
    PinFunction::IO(10),
    PinFunction::IO(9),
    PinFunction::IO(8),
    PinFunction::IO(7),
    PinFunction::IO(6),
    PinFunction::IO(5),
    PinFunction::IO(4),
    PinFunction::IO(3),
    PinFunction::IO(2),
    PinFunction::IO(1),
    PinFunction::IO(0),
    PinFunction::NC,
    PinFunction::VDD,
    // pin 51
    PinFunction::IO(78),
    PinFunction::IO(77),
    PinFunction::IO(76),
    PinFunction::IO(75),
    PinFunction::IO(74),
    PinFunction::IO(73),
    PinFunction::IO(72),
    PinFunction::IO(71),
    PinFunction::IO(70),
    PinFunction::IO(69),
    PinFunction::IO(68),
    PinFunction::IO(67),
    PinFunction::IO(66),
    PinFunction::IO(65),
    PinFunction::IO(64),
    PinFunction::IO(63),
    PinFunction::IO(62),
    PinFunction::IO(61),
    PinFunction::IO(60),
    PinFunction::IO(59),
    PinFunction::IO(58),
    PinFunction::IO(57),
    PinFunction::IO(56), // NOTE: datasheet has an error here?
    PinFunction::GND,
    PinFunction::VDD,
    // pin 76
    PinFunction::IO(55),
    PinFunction::IO(54),
    PinFunction::IO(53),
    PinFunction::IO(52),
    PinFunction::IO(51),
    PinFunction::IO(50),
    PinFunction::IO(49),
    PinFunction::IO(48),
    PinFunction::IO(47),
    PinFunction::IO(46),
    PinFunction::IO(45),
    PinFunction::IO(44),
    PinFunction::IO(43),
    PinFunction::IO(42),
    PinFunction::IO(41),
    PinFunction::IO(40),
    PinFunction::IO(39),
    PinFunction::IO(38),
    PinFunction::Special("BOOT0"),
    PinFunction::IO(37),
    PinFunction::IO(36),
    PinFunction::IO(35),
    PinFunction::IO(34),
    PinFunction::GND,
    PinFunction::VDD,
];

pub const AGRV2K_QFP64_PINS: [PinFunction; 64] = [
    // pin 1
    PinFunction::Special("VBAT"),
    PinFunction::IO(28),
    PinFunction::Special("OSC32_IN"),
    PinFunction::Special("OSC32_OUT"),
    PinFunction::Special("OSC_IN"),
    PinFunction::Special("OSC_OUT"),
    PinFunction::Special("nRST"),
    PinFunction::IO(27),
    PinFunction::IO(26),
    PinFunction::IO(25),
    PinFunction::IO(24),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(21), // note reordering here
    PinFunction::IO(22),
    PinFunction::IO(23),
    // pin 17
    PinFunction::IO(20),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(19),
    PinFunction::IO(18),
    PinFunction::IO(17),
    PinFunction::IO(16),
    PinFunction::IO(15),
    PinFunction::IO(14),
    PinFunction::IO(13),
    PinFunction::IO(12),
    PinFunction::IO(11),
    PinFunction::IO(7),
    PinFunction::IO(6),
    PinFunction::IO(0),
    PinFunction::VDD,
    // pin 33
    PinFunction::IO(78),
    PinFunction::IO(77),
    PinFunction::IO(76),
    PinFunction::IO(75),
    PinFunction::IO(66),
    PinFunction::IO(65),
    PinFunction::IO(64),
    PinFunction::IO(63),
    PinFunction::IO(62),
    PinFunction::IO(61),
    PinFunction::IO(60),
    PinFunction::IO(59),
    PinFunction::IO(58),
    PinFunction::IO(57),
    PinFunction::IO(56),
    PinFunction::VDD,
    // pin 49
    PinFunction::IO(55),
    PinFunction::IO(54),
    PinFunction::IO(53),
    PinFunction::IO(52),
    PinFunction::IO(51),
    PinFunction::IO(48),
    PinFunction::IO(42),
    PinFunction::IO(41),
    PinFunction::IO(40),
    PinFunction::IO(39),
    PinFunction::IO(38),
    PinFunction::Special("BOOT0"),
    PinFunction::IO(37),
    PinFunction::IO(36),
    PinFunction::GND,
    PinFunction::VDD,
];

pub const AGRV2K_QFP64H_PINS: [PinFunction; 64] = [
    // pin 1
    PinFunction::Special("VBAT"),
    PinFunction::IO(28),
    PinFunction::Special("OSC32_IN"),
    PinFunction::Special("OSC32_OUT"),
    PinFunction::Special("OSC_IN"),
    PinFunction::Special("OSC_OUT"),
    PinFunction::Special("nRST"),
    PinFunction::IO(27),
    PinFunction::IO(26),
    PinFunction::IO(25),
    PinFunction::IO(24),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(21), // note reordering here
    PinFunction::IO(22),
    PinFunction::IO(23),
    // pin 17
    PinFunction::IO(20),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(18),
    PinFunction::IO(16),
    PinFunction::Special("HRAM_RWDS"),
    PinFunction::IO(14),
    PinFunction::IO(12),
    PinFunction::IO(11),
    PinFunction::IO(10),
    PinFunction::IO(8),
    PinFunction::IO(6),
    PinFunction::IO(4),
    PinFunction::VDD,
    PinFunction::GND,
    PinFunction::VDD,
    // pin 33
    PinFunction::IO(78),
    PinFunction::IO(77),
    PinFunction::IO(76),
    PinFunction::IO(75),
    PinFunction::IO(66),
    PinFunction::IO(65),
    PinFunction::IO(64),
    PinFunction::IO(63),
    PinFunction::IO(62),
    PinFunction::IO(61),
    PinFunction::IO(60),
    PinFunction::IO(59),
    PinFunction::IO(58),
    PinFunction::IO(57),
    PinFunction::IO(56),
    PinFunction::VDD,
    // pin 49
    PinFunction::IO(55),
    PinFunction::IO(54),
    PinFunction::IO(53),
    PinFunction::IO(52),
    PinFunction::IO(51),
    PinFunction::IO(48),
    PinFunction::IO(42),
    PinFunction::IO(41),
    PinFunction::IO(40),
    PinFunction::IO(39),
    PinFunction::IO(38),
    PinFunction::Special("BOOT0"),
    PinFunction::IO(37),
    PinFunction::IO(36),
    PinFunction::GND,
    PinFunction::VDD,
];

pub const AGRV2K_QFP48_PINS: [PinFunction; 48] = [
    // pin 1
    PinFunction::Special("VBAT"),
    PinFunction::IO(28),
    PinFunction::Special("OSC32_IN"),
    PinFunction::Special("OSC32_OUT"),
    PinFunction::Special("OSC_IN"),
    PinFunction::Special("OSC_OUT"),
    PinFunction::Special("nRST"),
    PinFunction::GND,
    PinFunction::VDD,
    PinFunction::IO(21), // note reordering here
    PinFunction::IO(22),
    PinFunction::IO(23),
    // pin 13
    PinFunction::IO(20),
    PinFunction::IO(19),
    PinFunction::IO(18),
    PinFunction::IO(17),
    PinFunction::IO(16),
    PinFunction::IO(13),
    PinFunction::IO(12),
    PinFunction::IO(11),
    PinFunction::IO(1),
    PinFunction::IO(0),
    PinFunction::GND,
    PinFunction::VDD,
    // pin 25
    PinFunction::IO(78),
    PinFunction::IO(77),
    PinFunction::IO(76),
    PinFunction::IO(75),
    PinFunction::IO(62),
    PinFunction::IO(61),
    PinFunction::IO(60),
    PinFunction::IO(59),
    PinFunction::IO(58),
    PinFunction::IO(57),
    PinFunction::IO(56),
    PinFunction::VDD,
    // pin 37
    PinFunction::IO(55),
    PinFunction::IO(54),
    PinFunction::IO(42),
    PinFunction::IO(41),
    PinFunction::IO(40),
    PinFunction::IO(39),
    PinFunction::IO(38),
    PinFunction::Special("BOOT0"),
    PinFunction::IO(37),
    PinFunction::IO(36),
    PinFunction::GND,
    PinFunction::VDD,
];

pub const AGRV2K_QFN32_PINS: [PinFunction; 32] = [
    // pin 1
    PinFunction::IO(28),
    PinFunction::IO(24),
    PinFunction::IO(27),
    PinFunction::Special("nRST"),
    PinFunction::IO(25),
    PinFunction::VDD,
    PinFunction::IO(21), // note reordering here
    PinFunction::IO(22),
    // pin 9
    PinFunction::IO(23),
    PinFunction::IO(20),
    PinFunction::IO(19),
    PinFunction::IO(18),
    PinFunction::IO(17),
    PinFunction::IO(16),
    PinFunction::IO(11),
    PinFunction::VDD,
    // pin 17
    PinFunction::GND,
    PinFunction::IO(76),
    PinFunction::IO(74),
    PinFunction::IO(61),
    PinFunction::IO(60),
    PinFunction::IO(59),
    PinFunction::IO(58),
    PinFunction::IO(57),
    // pin 25
    PinFunction::IO(55),
    PinFunction::IO(54),
    PinFunction::IO(42),
    PinFunction::IO(41),
    PinFunction::IO(40),
    PinFunction::Special("BOOT0"),
    PinFunction::IO(36),
    PinFunction::VDD,
];
